### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by jackPanyj** [Jam3/devtool#61] opened 2016-05-07 03:07 UTC
when i install  this to run npm i -g devtool , it reports this

`Downloading electron-v0.37.8-linux-x64.zip
Error: socket hang up
/home/yanjie/.nvm/versions/node/v6.0.0/lib/node_modules/devtool/node_modules/electron-prebuilt/install.js:22
  throw err
  ^

Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1087:19)
    at TLSSocket.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
/home/yanjie/.nvm/versions/node/v6.0.0/lib
└── (empty)

npm WARN optional Skipping failed optional dependency /devtool/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/home/yanjie/.nvm/versions/node/v6.0.0/bin/node" "/home/yanjie/.nvm/versions/node/v6.0.0/bin/npm" "install" "-g" "devtool"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@0.37.8 postinstall: `node install.js`
npm ERR! Exit status 1
`

**Comment by mattdesl** [comment] 2016-05-30 13:48
I can't reproduce this – seems like an issue with electron-prebuilt. We have since moved to a much newer version. If the issue persists please post in [electron-prebuilt](https://github.com/electron-userland/electron-prebuilt) issues.

Closing for now.

**Closed by mattdesl** 2016-05-30 13:48 UTC
