### ISSUE TITLE
Refuses to launch for non `js` files

### ISSUE THREAD

**Issue by jtheoof** [Jam3/devtool#10] opened 2016-01-20 16:36 UTC
Running:

```
$ devtool grunt concat
Error: ENOENT: no such file or directory, stat 'grunt.js'
    at Error (native)
```

Also:

```
$ devtool /usr/local/bin/grunt concat
Error: ENOENT: no such file or directory, stat '/usr/local/bin/grunt.js'
    at Error (native)
```

So it looks like `devtool` is really expecting a `js` file but should accept any `node` file.

**Comment by halhenke** [comment] 2016-01-20 16:52
Yep, heres the relevant code:

https://github.com/Jam3/devtool/blob/master/server.js#L77-L79

**Comment by mattdesl** [comment] 2016-01-20 18:12
The same problem happens when you do this:

```sh
node gulp watch
```

Because `gulp` is not a file that can be found. Instead, you will have to do this:

```sh
node node_modules/gulp/bin/gulp.js watch
```

Or, with `devtool@1.2.1` or newer:

```sh
devtool node_modules/gulp/bin/gulp.js -c -- wach
``` 

Hope that clears things up. :smile:

**Comment by mattdesl** [comment] 2016-01-21 16:43
Closing this since it's not a bug.

Latest code also improves the entry file resolving so it works just like `node foo/` (and will look for `index.js`).

**Closed by mattdesl** 2016-01-21 16:43 UTC
